### ISSUE TITLE
Ange explicit diareienummer

### ISSUE THREAD

**Issue by Ainali** [Forsakringskassan/riktlinje-oppenkallkod#3]
I [README.md](https://github.com/Forsakringskassan/riktlinje-oppenkallkod/blob/master/README.md) anges att det finns ett diariefört formellt styrdokument. För att göra det lättare för andra att hänvisa till det bör diarienumret skrivas ut explicit.

**Comment by tlagrenfkit** [comment]
Hej och tack för återkoppling. Det var ingenting vi eller någon annan föreslagit men jag tycker det var ett jättebra förslag, det är enklare för alla om det är så. Jag har uppdaterat README.md så den innehåller aktuellt diarienummer.
